### ISSUE TITLE
Transaction Details

### ISSUE THREAD

**Issue by peterpeter** [wallee-payment/php-sdk#14]
Sorry to bother you on this way, but I stuck somehow (and yes, I have read the documentary)
On the payment-response-page I run this code to check the transaction state:

    $client = new \Wallee\Sdk\ApiClient($userId, $applicationKey);
    $transactionService = new \Wallee\Sdk\Service\TransactionService($client);
    $trData             = $transactionService->read($spaceId, $tranactionId);
    $state              = $trData->getState();

But if the payment is successful I need some more details of the transaction, e.g. (Cardholder-Name, Cardbrand and -number, Card valid until....) 

How can get those details?
Can someone point me in the right direction? 
That would be nice

Roger

**Comment by theodorspringwallee** [comment]
Dear Roger

Thank you for your question.

On our wallee API documentation you can see that there are methods to get the specific payment method brand (connector ID is on the transaction object, which should tell you if you are using e.g. Visa or Mastercard).

On Wallee itself we are only saving the masked card number and the expiry date (you can get them via: https://app-wallee.com/doc/api/web-service#charge-attempt-service--search).

The unmasked card number, the cardholder name, etc. are saved on the connected processor you're using (e.g. Concardis, Computop, etc.). If a token for a concerned transaction is set it should be possible to use these data for recurring payments or to select them in the checkout for further manual payments.

Since your case seems to be a usual support case please contact our support for further help: info@wallee.com (Please mention there this git issue link)
With this regular process we can forward your question to our developers to give you a final answer to the still opened points.

Nevertheless, I still hope, I could help you to get a bit forward with my given answers.
Therefore, this git issue will be closed.

Best regards
Theodor

**Comment by peterpeter** [comment]
Hi Theodor
Thank you for your detailed response. As you suggested, I have forwarded this request to wallee.com.
Regards
Roger
